### ISSUE TITLE
problem with current grunt-contrib-imagemin version in package.json

### ISSUE THREAD

**Issue by tommaton** [TryKickoff/kickoff#66] opened 2015-11-19 21:01 UTC
Hi Guys,

It seems that there is a problem with the current grunt-contrib-imagemin, when you do a build it fails.

You'll need to upgrade the version from 0.9.4 -> 1.0.0 and then the grunt builds work again.

Tom

**Comment by mrmartineau** [comment] 2015-11-19 22:43
Hi @tommaton, we are aware of the issue & have fixed it in the imminent v6.0.0 release. I'm going to close this because dupe of #65

**Closed by mrmartineau** 2015-11-19 22:43 UTC

**Comment by mrmartineau** [comment] 2015-11-20 06:43
@tommaton have you seen the work we're doing for v6.0.0? the new generator can be installed using `npm i -g generator-kickoff@next` or the next branch here has everything too. We are very close to releasing it and would value your opinion.

**Comment by tommaton** [comment] 2015-11-20 13:52
@mrmartineau never saw the new version, I'll take a look as just starting a new project so will give it a go and give you any feedback I have.

**Comment by ashleynolan** [comment] 2015-11-20 14:56
@tommaton That’d be cool – we’re looking at releasing it early next week, so if you find any issues let us know :+1:

**Comment by tommaton** [comment] 2015-11-20 16:06
@mrmartineau @ashleynolan when updating the generator to v6 it still seems to be installing v5 when running the yo kickoff command.

I've uninstalled the generator, cleared the npm cache etc and then reinstalled.

Any ideas?

**Comment by mrmartineau** [comment] 2015-11-20 16:22
umm, not sure. Was going to suggest you uninstall. I am about to push another `@next` version very shortly so I'll respond again when I do. Sorry mate

**Comment by mrmartineau** [comment] 2015-11-20 16:47
Hi @tommaton, I have just published a new, tagged version of the generator. Please try installing it again..
