### ISSUE TITLE
Error in styleguide.scss

### ISSUE THREAD

**Issue by nicbell** [TryKickoff/kickoff#88] opened 2016-05-03 13:42 UTC
styleguide.scss line 211
```
		@extend .interfaceType;
		@extend .interfaceType-subtle;
```
Should be.
```
		@extend .sg-interfaceType;
		@extend .sg-interfaceType--subtle;
```
It's fixed on `next` branch but not on `master`. 
It breaks the build of the styleguide. Should there be a patch release?

**Comment by mrmartineau** [comment] 2016-05-03 14:28
thanks, I found this recently. I think it is fixed in `next` branch already

**Comment by ashleynolan** [comment] 2016-05-03 14:38
Yeh, it is.  It’s caused by the latest node-sass updates in error reporting

**Comment by nicbell** [comment] 2016-05-03 16:24
@mrmartineau I hear it's fixed in the `next` branch.

**Closed** 2016-06-09 06:41 UTC
